runtime: python311

# Set App Engine instance class
# See https://cloud.google.com/appengine/docs/standard/#instance_classes
instance_class: F1


handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto

- url: /static/.*
  static_dir: static

automatic_scaling:
  max_concurrent_requests: 10

# set envvars from local file not in the repo
includes:
  - env_vars.yaml
